version: "3"
services:
  consul:
    image: "consul:1.15.4"
    container_name: gomall_consul
    ports:
      - "8500:8500"
  mysql:
    image: "mysql:8.0"
    container_name: gomall_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gomall
  redis:
    image: "redis:6.2"
    container_name: gomall_redis
    ports:
      - "6379:6379"
      