// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	order "github.com/A1sca/Douyin-Mall-Go/app/api/biz/router/order"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)
}
